###################
# TravisCI config #
###################
os: linux
dist: bionic
language: php
php: 7.3


##############
# Git config #
##############
git:
  depth: false
  submodules: false
  quiet: true


jobs:
  include:
    - stage: test
      install:
        - composer install || exit 1

      script:
        - echo 'test'

    - stage: build
      install:
        - composer install --no-dev || exit 1

      script:
        - echo 'build'


    - stage: deploy
      script:
        - echo 'deploy'


stages:
  - name: test
  - name: build
  - name: deploy
    if: branch = main
